# Generated by Django 3.2.13 on 2022-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_comy', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
